# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - run: npm install
    
    - name: Cleanup
      run: rm -rf docs

    - name: Build
      run: npm run deploy
      
    - name: Deploy
      uses: EndBug/add-and-commit@v4
      with:
        message: "GitHub Pages deploy"
        add: "docs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
